HR.Presentation/Areas/Manager/Controllers/RequestController.cs
using AutoMapper;
using HR.Application.Features.AdvancePayments.Commands.ApproveAdvancePayment;
using HR.Application.Features.AdvancePayments.Commands.RejectAdvancePayment;
using HR.Application.Features.AdvancePayments.Queries.GetAdvancePaymentListByCompanyId;
using HR.Application.Features.Expenditures.Commands.ApproveExpenditureRequest;
using HR.Application.Features.Expenditures.Commands.RejectExpenditureRequest;
using HR.Application.Features.Expenditures.Queries.GetExpenditureRequestListByCompanyId;
using HR.Application.Features.People.Queries.GetPerson;
using HR.Application.Features.Permission.Command.ApprovePermissionRequest;
using HR.Application.Features.Permission.Command.RejectPermissionRequest;
using HR.Application.Features.Permission.Queries.GetPermissionRequestListByCompanyId;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace HR.Presentation.Areas.Manager.Controllers
{
    [Area("Manager")]
    [Authorize(Roles = "Manager")]
    public class RequestController : Controller
    {
        private readonly IMediator mediator;
        private readonly IMapper mapper;
        private readonly IWebHostEnvironment hostEnvironment;

        public RequestController(IMediator mediator, IMapper mapper, IWebHostEnvironment hostEnvironment)
        {
            this.mediator = mediator;
            this.mapper = mapper;
            this.hostEnvironment = hostEnvironment;
        }


        // İzin Talep Onay İşlemleri
        public async Task<IActionResult> PermissionRequestApprove()
        {
            GetPersonByIdQuery query = new GetPersonByIdQuery() { Id = Guid.Parse(HttpContext.Session.GetString("PersonnelId")) };
            var result = await mediator.Send(query);
            ViewBag.UserProfilePicture = result.Photo;
            //ViewBag.UserProfileId = result.Id;

            var list = await mediator.Send(new GetPermissionRequestListByCompanyIdQuery() { CompanyId = result.CompanyId });
            return View(list);
        }

        [HttpGet]
        public async Task<IActionResult> ApproveByIdPermissionRequest(Guid permissionRequestId)
        {
            var result = await mediator.Send(new ApprovePermissionRequestCommand() { PermissionRequestId = permissionRequestId });
            return RedirectToAction("PermissionRequestApprove");
        }

        [HttpGet]
        public async Task<IActionResult> RejectByIdPermissionRequest(Guid permissionRequestId)
        {
            var result = await mediator.Send(new RejectPermissionRequestCommand() { PermissionRequestId = permissionRequestId });
            return RedirectToAction("PermissionRequestApprove");
        }


        // Harcama Talep Onay İşlemleri
        public async Task<IActionResult> ExpenditureRequestApprove()
        {
            GetPersonByIdQuery query = new GetPersonByIdQuery() { Id = Guid.Parse(HttpContext.Session.GetString("PersonnelId")) };
            var result = await mediator.Send(query);
            ViewBag.UserProfilePicture = result.Photo;
            //ViewBag.UserProfileId = result.Id;

            var list = await mediator.Send(new GetExpenditureRequestListByCompanyIdQuery() { CompanyId = result.CompanyId });
            return View(list);
        }

        [HttpGet]
        public async Task<IActionResult> ApproveByIdExpenditureRequest(Guid expenditureRequestId)
        {
            var result = await mediator.Send(new ApproveExpenditureRequestCommand() { ExpenditureId = expenditureRequestId });
            return RedirectToAction("ExpenditureRequestApprove");
        }

        [HttpGet]
        public async Task<IActionResult> RejectByIdExpenditureRequest(Guid expenditureRequestId)
        {
            var result = await mediator.Send(new RejectExpenditureRequestCommand() { ExpenditureId = expenditureRequestId });
            return RedirectToAction("ExpenditureRequestApprove");
        }

        public IActionResult ViewDocument(string documentPath)
        {
            if (!string.IsNullOrEmpty(documentPath))
            {
                string filePath = Path.Combine(hostEnvironment.WebRootPath, "expenditureFile", documentPath);
                if (System.IO.File.Exists(filePath))
                {
                    byte[] fileBytes = System.IO.File.ReadAllBytes(filePath);
                    string contentType = GetContentType(documentPath); // Belge türüne bağlı olarak MIME türünü al
                    string fileName = Path.GetFileName(documentPath);

                    return File(fileBytes, contentType);
                }
                else
                {
                    return NotFound();
                }
            }
            return NotFound();
        }
        private string GetContentType(string fileName)
        {
            string ext = Path.GetExtension(fileName)?.ToLowerInvariant();
            switch (ext)
            {
                case ".pdf":
                    return "application/pdf";
                case ".jpg":
                    return "image/jpeg";
                case ".jpeg":
                    return "image/jpeg";
                case ".png":
                    return "image/png";
                default:
                    return "application/octet-stream"; // Varsayılan MIME türü
            }
        }

        // Avans Talep Onay İşlemleri
        public async Task<IActionResult> AdvancePaymentRequestApprove()
        {
            GetPersonByIdQuery query = new GetPersonByIdQuery() { Id = Guid.Parse(HttpContext.Session.GetString("PersonnelId")) };
            var result = await mediator.Send(query);
            ViewBag.UserProfilePicture = result.Photo;
            //ViewBag.UserProfileId = result.Id;

            var list = await mediator.Send(new GetAdvancePaymentListByCompanyIdQuery() { CompanyId = result.CompanyId });
            return View(list);
        }

        [HttpGet]
        public async Task<IActionResult> ApproveByIdAdvancePaymentRequest(Guid advancePaymentId)
        {
            var result = await mediator.Send(new ApproveAdvancePaymentCommand() { AdvancePaymentId = advancePaymentId });
            return RedirectToAction("AdvancePaymentRequestApprove");
        }

        [HttpGet]
        public async Task<IActionResult> RejectByIdAdvancePaymentRequest(Guid advancePaymentId)
        {
            var result = await mediator.Send(new RejectAdvancePaymentCommand() { AdvancePaymentId = advancePaymentId });
            return RedirectToAction("AdvancePaymentRequestApprove");
        }
    }
}

HR.Presentation/Areas/Manager/Views/Request/AdvancePaymentRequestApprove.cshtml
@using HR.Application.Features.EnumViewModels
@model IEnumerable<HR.Application.Features.AdvancePayments.ViewModels.AdvancePaymentApproveListVM>

@{
    ViewData["Title"] = "Avans Talepleri Onaylama";
    Layout = "~/Areas/Manager/Views/Shared/_ManagerLayout.cshtml";
}

<div class="col-lg-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title" style="color:saddlebrown; font-weight:bold">PERSONEL AVANS TALEPLERİ</h4>

            <div class="btn-group btn-md mb-3">
                <button type="button" class="btn btn-inverse-info" onclick="applyFilter('Onay Bekliyor')">Onay Bekliyor</button>
                <button type="button" class="btn btn-inverse-success" onclick="applyFilter('Onaylandı')">Onaylandı</button>
                <button type="button" class="btn btn-inverse-danger" onclick="applyFilter('Reddedildi')">Reddedildi</button>
                <button type="button" class="btn btn-inverse-secondary" onclick="clearFilters()">Hepsi</button>
            </div>

            <div class="table-responsive">
                <table class="table table-hover" id="myTable">
                    <thead>
                        <tr>
                            <th hidden>
                                @Html.DisplayNameFor(model => model.Id)
                            </th>
                            <th>
                                Talep Eden
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.AdvanceType)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Amount)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.CurrencyType)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.CreatedDate)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.ApprovalStatus)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.ApprovalDate)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Description)
                            </th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td hidden>
                                    @Html.DisplayFor(modelItem => item.Id)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Personnel.Name) @Html.DisplayFor(modelItem => item.Personnel.SecondName) @Html.DisplayFor(modelItem => item.Personnel.Surname) @Html.DisplayFor(modelItem => item.Personnel.SecondSurname)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.AdvanceType)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Amount)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.CurrencyType)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.CreatedDate)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.ApprovalStatus)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.ApprovalDate)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Description)
                                </td>
                                <td>
                                    @if (item.ApprovalStatus == ApprovalStatusVM.ApprovalWaiting)
                                    {
                                        <button href="#" onclick="approveAdvancePayment('@item.Id')" class="btn btn-inverse-success btn-icon"><i class="ti-check"></i></button>
                                        <button href="#" onclick="rejectAdvancePayment('@item.Id')" class="btn btn-inverse-danger btn-icon"><i class="ti-close"></i></button>
                                    }
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script type="text/javascript">

        function approveAdvancePayment(advancePaymentId) {
            var confirmDelete = confirm("Avans talebini onaylamak istediğinizden emin misiniz?");

            if (confirmDelete) {
                window.location.href = '/Manager/Request/ApproveByIdAdvancePaymentRequest?advancePaymentId=' + advancePaymentId;
            }
        }

        function rejectAdvancePayment(advancePaymentId) {
            var confirmDelete = confirm("Avans talebini reddetmek istediğinizden emin misiniz?");

            if (confirmDelete) {
                window.location.href = '/Manager/Request/RejectByIdAdvancePaymentRequest?advancePaymentId=' + advancePaymentId;
            }
        }



        var table;

        $(document).ready(function () {
            table = $('#myTable').DataTable({
                "language": {
                    "url": '//cdn.datatables.net/plug-ins/1.13.7/i18n/tr.json',
                }
            });

            // Sayfa yüklendiğinde "Onay Bekliyor" butonuna otomatik olarak tıkla
            applyFilter('Onay Bekliyor');
        });

        function applyFilter(status) {
            table.column(6).search(status).draw();
        }

        function clearFilters() {
            table.column(6).search('').draw();
        }
    </script>
}

HR.Presentation/Areas/Manager/Views/Request/ExpenditureRequestApprove.cshtml
@using HR.Application.Features.EnumViewModels
@model IEnumerable<HR.Application.Features.Expenditures.ViewModels.ExpenditureApproveListVM>

@{
    ViewData["Title"] = "Harcama Talepleri Onaylama";
    Layout = "~/Areas/Manager/Views/Shared/_ManagerLayout.cshtml";
}

<div class="col-lg-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title" style="color:saddlebrown; font-weight:bold">PERSONEL HARCAMA TALEPLERİ</h4>

            <div class="btn-group btn-md mb-3">
                <button type="button" class="btn btn-inverse-info" onclick="applyFilter('Onay Bekliyor')">Onay Bekliyor</button>
                <button type="button" class="btn btn-inverse-success" onclick="applyFilter('Onaylandı')">Onaylandı</button>
                <button type="button" class="btn btn-inverse-danger" onclick="applyFilter('Reddedildi')">Reddedildi</button>
                <button type="button" class="btn btn-inverse-secondary" onclick="clearFilters()">Hepsi</button>
            </div>

            <div class="table-responsive">
                <table class="table table-hover" id="myTable">
                    <thead>
                        <tr>
                            <th hidden>
                                @Html.DisplayNameFor(model => model.Id)
                            </th>
                            <th>
                                Talep Eden
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Amount)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.CurrencyType)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.ExchangeAmount)
                            </th>

                            <th>
                                @Html.DisplayNameFor(model => model.ApprovedDate)
                            </th>

                            <th>
                                Belge Görüntüle
                            </th>

                            <th>
                                @Html.DisplayNameFor(model => model.ApprovalStatus)
                            </th>

                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td hidden>
                                    @Html.DisplayFor(modelItem => item.Id)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Personnel.Name) @Html.DisplayFor(modelItem => item.Personnel.SecondName) @Html.DisplayFor(modelItem => item.Personnel.Surname) @Html.DisplayFor(modelItem => item.Personnel.SecondSurname)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Amount)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.CurrencyType)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.ExchangeAmount)
                                </td>

                                <td>
                                    @Html.DisplayFor(modelItem => item.ApprovedDate)
                                </td>

                                <td>
                                    @if (!string.IsNullOrEmpty(item.Document))
                                    {
                                        <a href="@Url.Action("ViewDocument", "Request", new { documentPath = item.Document })" class="btn btn-icon" target="_blank" style="display: flex; align-items: center; padding: 5px;">
                                            <i class="ti-eye" style="margin-right: 5px; font-size: 1.2em;"></i>
                                            <span style="font-size: 1em;">Görüntüle</span>
                                        </a>
                                    }
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.ApprovalStatus)
                                </td>
                                <td>
                                    @if (item.ApprovalStatus == ApprovalStatusVM.ApprovalWaiting)
                                    {
                                        <button href="#" onclick="approveExpenditureRequest('@item.Id')" class="btn btn-inverse-success btn-icon"><i class="ti-check"></i></button>
                                        <button href="#" onclick="rejectExpenditureRequest('@item.Id')" class="btn btn-inverse-danger btn-icon"><i class="ti-close"></i></button>
                                    }
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>

            </div>
        </div>

    </div>
</div>


@section Scripts {
    <script type="text/javascript">

        function approveExpenditureRequest(expenditureRequestId) {
            var confirmDelete = confirm("Harcama talebini onaylamak istediğinizden emin misiniz?");

            if (confirmDelete) {
                window.location.href = '/Manager/Request/ApproveByIdExpenditureRequest?expenditureRequestId=' + expenditureRequestId;
            }
        }

        function rejectExpenditureRequest(expenditureRequestId) {
            var confirmDelete = confirm("Harcama talebini reddetmek istediğinizden emin misiniz?");

            if (confirmDelete) {
                window.location.href = '/Manager/Request/RejectByIdExpenditureRequest?expenditureRequestId=' + expenditureRequestId;
            }
        }



        var table;

        $(document).ready(function () {
            table = $('#myTable').DataTable({
                "language": {
                    "url": '//cdn.datatables.net/plug-ins/1.13.7/i18n/tr.json',
                }
            });

            // Sayfa yüklendiğinde "Onay Bekliyor" butonuna otomatik olarak tıkla
            applyFilter('Onay Bekliyor');
        });

        function applyFilter(status) {
            table.column(7).search(status).draw();
        }

        function clearFilters() {
            table.column(7).search('').draw();
        }
    </script>
}

HR.Presentation/Areas/Manager/Views/Request/PermissionRequestApprove.cshtml
@using HR.Application.Features.EnumViewModels
@model IEnumerable<HR.Application.Features.Permission.ViewModels.PermissionRequestApproveListVM>

@{
    ViewData["Title"] = "İzin Talepleri Onaylama";
    Layout = "~/Areas/Manager/Views/Shared/_ManagerLayout.cshtml";

}

<div class="col-lg-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title" style="color:saddlebrown; font-weight:bold">PERSONEL İZİN TALEPLERİ </h4>

            <div class="btn-group btn-md mb-3">
                <button type="button" class="btn btn-inverse-info" onclick="applyFilter('Onay Bekliyor')">Onay Bekliyor</button>
                <button type="button" class="btn btn-inverse-success" onclick="applyFilter('Onaylandı')">Onaylandı</button>
                <button type="button" class="btn btn-inverse-danger" onclick="applyFilter('Reddedildi')">Reddedildi</button>
                <button type="button" class="btn btn-inverse-secondary" onclick="clearFilters()">Hepsi</button>
            </div>

            <div class="table-responsive">
                <table class="table table-hover" id="myTable">
                    <thead>
                        <tr>
                            <th hidden>
                                @Html.DisplayNameFor(model => model.Id)
                            </th>
                            <th>
                                Talep Eden
                                @* @Html.DisplayNameFor(model => model.Personnel.Name) *@
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.StartDate)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.EndDate)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Days)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.ApprovalStatus)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.ApprovedDate)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.PermissionType.Name)
                            </th>
                            <th></th>
                        </tr>
                    </thead>

                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td hidden>
                                    @Html.DisplayFor(modelItem => item.Id)
                                </td>
                                <td>
                                    @* @Html.DisplayFor(modelItem => item.Personnel.Name) *@
                                    @Html.DisplayFor(modelItem => item.Personnel.Name) @Html.DisplayFor(modelItem => item.Personnel.SecondName) @Html.DisplayFor(modelItem => item.Personnel.Surname) @Html.DisplayFor(modelItem => item.Personnel.SecondSurname)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.StartDate)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.EndDate)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Days)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.ApprovalStatus)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.ApprovedDate)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.PermissionType.Name)
                                </td>

                                <td>
                                    @if (item.ApprovalStatus == ApprovalStatusVM.ApprovalWaiting)
                                    {
                                        <button href="#" onclick="approvePermissionRequest('@item.Id')" class="btn btn-inverse-success btn-icon"><i class="ti-check"></i></button>
                                        <button href="#" onclick="rejectPermissionRequest('@item.Id')" class="btn btn-inverse-danger btn-icon"><i class="ti-close"></i></button>
                                    }
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>

            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script type="text/javascript">

        function approvePermissionRequest(permissionRequestId) {
            var confirmDelete = confirm("İzin talebini onaylamak istediğinizden emin misiniz?");

            if (confirmDelete) {
                window.location.href = '/Manager/Request/ApproveByIdPermissionRequest?permissionRequestId=' + permissionRequestId;
            }
        }

        function rejectPermissionRequest(permissionRequestId) {
            var confirmDelete = confirm("İzin talebini reddetmek istediğinizden emin misiniz?");

            if (confirmDelete) {
                window.location.href = '/Manager/Request/RejectByIdPermissionRequest?permissionRequestId=' + permissionRequestId;
            }
        }



        var table;

        $(document).ready(function () {
            table = $('#myTable').DataTable({
                "language": {
                    "url": '//cdn.datatables.net/plug-ins/1.13.7/i18n/tr.json',
                }
            });

            // Sayfa yüklendiğinde "Onay Bekliyor" butonuna otomatik olarak tıkla
            applyFilter('Onay Bekliyor');
        });

        function applyFilter(status) {
            table.column(5).search(status).draw();
        }

        function clearFilters() {
            table.column(5).search('').draw();
        }
    </script>
}