HR.Presentation/Areas/Personnel/Controllers/PersonController.cs
using AutoMapper;
using HR.Application.Features.People.Commands.PersonUpdate;
using HR.Application.Features.People.Queries.GetPerson;
using HR.Application.Features.People.ViewModels;
using HR.Application.Features.Permission.Command.CreatePermissionRequest;
using HR.Application.Features.Permission.Queries;
using HR.Application.Features.Permission.Queries.GetPermissionTypesList;
using HR.Application.Features.Permission.ViewModels;
using HR.Domain.Concrete;
using HR.Presentation.Models;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace HR.Presentation.Areas.Person.Controllers;

[Authorize(Roles = "Personnel")]
[Area("Personnel")]

public class PersonController : Controller
{
    private readonly IMediator mediator;
    private readonly IMapper mapper;
    private readonly IWebHostEnvironment webHostEnvironment;

    public PersonController(IMediator mediator, IMapper mapper, IWebHostEnvironment webHostEnvironment)
    {
        this.mediator = mediator;
        this.mapper = mapper;
        this.webHostEnvironment = webHostEnvironment;
    }

    public async Task<IActionResult> Index()//GetPersonByIdQuery query)
    {
        GetPersonByIdQuery query = new GetPersonByIdQuery() { Id = Guid.Parse(HttpContext.Session.GetString("PersonnelId")) };
        var personnel = await mediator.Send(query);
        ViewBag.PersonnelProfilePicture = personnel.Photo;
        return View(personnel);
    }
    public async Task GetProfilePicturePath()
    {
        GetPersonByIdQuery query = new GetPersonByIdQuery() { Id = Guid.Parse(HttpContext.Session.GetString("PersonnelId")) };
        var personnel = await mediator.Send(query);
        ViewBag.PersonnelProfilePicture = personnel.Photo;
    }
    public async Task<IActionResult> UpdatePerson()//Guid id)
    {
        //GetPersonByIdQuery query = new GetPersonByIdQuery() { Id = id };
        GetPersonByIdQuery query = new GetPersonByIdQuery() { Id = Guid.Parse(HttpContext.Session.GetString("PersonnelId")) };
        var result = await mediator.Send(query);
        ViewBag.PersonnelProfilePicture = result.Photo;
        return View(result);
    }

    [HttpPost]
    public async Task<IActionResult> UpdatePerson(PersonUpdateCommand personUpdateCommand)
    {
        if (personUpdateCommand.PhotoFile != null)
        {
			personUpdateCommand.Photo = FileOperation.ReturnFileName(personUpdateCommand.PhotoFile, "photos", webHostEnvironment);
        }
        await mediator.Send(personUpdateCommand);
        return RedirectToAction("Index");
    }
    public async Task<IActionResult> Detail()//Guid id)
    {
        //GetPersonByIdQuery query = new GetPersonByIdQuery() { Id = id };
        GetPersonByIdQuery query = new GetPersonByIdQuery() { Id = Guid.Parse(HttpContext.Session.GetString("PersonnelId")) };
        var result = await mediator.Send(query);
        ViewBag.PersonnelProfilePicture = result.Photo;
        return View(result);
    }
    public async Task<IActionResult> PermissionRequestList()//Guid id)
    {
        //GetPermissionListQuery permissionList = new GetPermissionListQuery() { PersonelId = id };
        GetPermissionTypesListQuery permissionList = new GetPermissionTypesListQuery() { PersonnelId = Guid.Parse(HttpContext.Session.GetString("PersonnelId")) };
        var result = await mediator.Send(permissionList);
        GetProfilePicturePath();
        return View(result);
    }
    public async Task<IActionResult> CreatePermissionRequest()//Guid id)
    {
        //CreatePermissionRequestCommand command = new CreatePermissionRequestCommand() { PersonnelId = id };
        CreatePermissionRequestCommand command = new CreatePermissionRequestCommand() { PersonnelId = Guid.Parse(HttpContext.Session.GetString("PersonnelId")) };
        var result = await mediator.Send(command);
        GetProfilePicturePath();
        return View(command);
    }
    [HttpPost]
    public async Task<IActionResult> CreatePermissionRequest(PermissionRequestCreateVM permissionRequestCreateVM)
    {
        if (ModelState.IsValid)
        {
            return RedirectToAction("İzin oluşturuldu.");
        }
        return View(permissionRequestCreateVM);
    }
}

HR.Presentation/Areas/Personnel/Views/Person/Detail.cshtml
@using HR.Application.Features.People.ViewModels
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@model PersonDetailVM
@{
    ViewData["Title"] = "Personel Detay Bilgileri";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>

    .btn-primary {
        background-color: #5D54A4;
        border-color: mediumpurple;
        color: black;
    }

        .btn-primary:hover {
            background-color: mediumpurple;
            border-color: mediumpurple;
        }

    .btn-outline-primary {
        border-color: mediumpurple;
        color: #5D54A4;
    }

        .btn-outline-primary:hover {
            background-color: #5D54A4;
            border-color: mediumpurple;
            color: black;
        }
</style>
<section>
    <div class="container py-5">
        <div class="row">
            <div class="col-lg-4">
                <div class="card mb-4">
                    <div class="card-body text-center">
                        <img src="~/photos/@Model.Photo" alt="..."
                             class="rounded-circle img-fluid" style="width: 150px;">
                        <h5 class="my-3">@Model.Name @Model.SecondName @Model.Surname @Model.SecondSurname</h5>
                        <p class="text-muted mb-1">@Model.Job.Name</p>
                        <p class="text-muted mb-4">@Model.Department.Name</p>
                        <div class="d-flex justify-content-center mb-2">
                            <a asp-action="UpdatePerson" asp-controller="Person" asp-route-id="@Model.Id" class="btn btn-outline-primary">Güncelle</a>
                            <a asp-action="Detail" asp-controller="Person" asp-route-id="@Model.Id" class="btn btn-primary ms-1">Detay</a> 
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-lg-8">
                <div class="card mb-4 ">
                    <div class="card-body rounded-3">

                        <div class="row">
                            <div class="col-sm-3">
                                <p class="mb-0">Tam Adı</p>
                            </div>
                            <div class="col-sm-9">
                                <p class="text-muted mb-0">@Model.Name @Model.SecondName @Model.Surname @Model.SecondSurname</p>
                            </div>
                        </div>

                        <hr>
                        <div class="row">
                            <div class="col-sm-3">
                                <p class="mb-0">Kimlik Numarası</p>
                            </div>
                            <div class="col-sm-9">
                                <p class="text-muted mb-0">@Model.IdentityNumber</p>
                            </div>
                        </div>

                        <hr>
                        <div class="row">
                            <div class="col-sm-3">
                                <p class="mb-0">Doğum Tarihi</p>
                            </div>
                            <div class="col-sm-9">
                                <p class="text-muted mb-0">@Model.BirthDate.ToString("dd.MM.yyyy")</p>
                            </div>
                        </div>

                        <hr>
                        <div class="row">
                            <div class="col-sm-3">
                                <p class="mb-0">Doğum Yeri</p>
                            </div>
                            <div class="col-sm-9">
                                <p class="text-muted mb-0">@Model.PlaceofBirth</p>
                            </div>
                        </div>

                        <hr>
                        <div class="row">
                            <div class="col-sm-3">
                                <p class="mb-0">E-mail</p>
                            </div>
                            <div class="col-sm-9">
                                <p class="text-muted mb-0">@Model.EMail</p>
                            </div>
                        </div>

                        <hr>
                        <div class="row">
                            <div class="col-sm-3">
                                <p class="mb-0">Telefon Numarası</p>
                            </div>
                            <div class="col-sm-9">
                                <p class="text-muted mb-0">@Model.PhoneNumber</p>
                            </div>
                        </div>

                        <hr>
                        <div class="row">
                            <div class="col-sm-3">
                                <p class="mb-0">Adres</p>
                            </div>
                            <div class="col-sm-9">
                                <p class="text-muted mb-0">@Model.Address</p>
                            </div>
                        </div>

                        <hr>
                        <div class="row">
                            <div class="col-sm-3">
                                <p class="mb-0">Çalıştığı Kurum</p>
                            </div>
                            <div class="col-sm-9">
                                <p class="text-muted mb-0">@Model.CompanyName</p>
                            </div>
                        </div>

                        <hr>
                        <div class="row">
                            <div class="col-sm-3">
                                <p class="mb-0">İşe Başlangıç Tarihi</p>
                            </div>
                            <div class="col-sm-9">
                                <p class="text-muted mb-0">@Model.HireDate.ToString("dd.MM.yyyy")</p>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

HR.Presentation/Areas/Personnel/Views/Person/Index.cshtml
@using HR.Application.Features.People.ViewModels
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@model PersonDetailVM

@{
    ViewData["Title"] = "Personel - Anasayfa";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>

    .btn-primary {
        background-color: #5D54A4;
        border-color: mediumpurple;
        color: black;
        
        
    }

        .btn-primary:hover {
            background-color: mediumpurple;
            border-color: mediumpurple;
        }
</style>
    

<section>
    <div class="container py-5">
        <div class="row">
            <div class="col-lg-4">
                <div class="card mb-4">
                    <div class="card-body text-center">
                        <img src="~/photos/@Model.Photo" alt="..."
                             class="rounded-circle img-fluid" style="width: 150px;">
                        <h5 class="my-3">@Model.Name @Model.SecondName @Model.Surname @Model.SecondSurname</h5>
                        <p class="text-muted mb-1">@Model.Job.Name</p>
                        <p class="text-muted mb-4">@Model.Department.Name</p>
                        <div class="d-flex justify-content-center mb-2">
                            <a asp-action="UpdatePerson" asp-area="Personnel" asp-controller="Person"  asp-route-id="@Model.Id" class="btn btn-primary">Güncelle</a>
                            <a asp-action="Detail" asp-controller="Person" asp-route-id="@Model.Id" class="btn btn-primary ms-1">Detay</a>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-lg-8">
                <div class="card mb-4 ">
                    <div class="card-body rounded-3">
                        <div class="row">
                            <div class="col-sm-3">
                                <p class="mb-0">Tam Adı</p>
                            </div>
                            <div class="col-sm-9">
                                <p class="text-muted mb-0">@Model.Name @Model.SecondName @Model.Surname @Model.SecondSurname</p>
                            </div>
                        </div>
                        <hr>
                        <div class="row">
                            <div class="col-sm-3">
                                <p class="mb-0">E-mail</p>
                            </div>
                            <div class="col-sm-9">
                                <p class="text-muted mb-0">@Model.EMail</p>
                            </div>
                        </div>
                        <hr>
                        <div class="row">
                            <div class="col-sm-3">
                                <p class="mb-0">Telefon Numarası</p>
                            </div>
                            <div class="col-sm-9">
                                <p class="text-muted mb-0">@Model.PhoneNumber</p>
                            </div>
                        </div>
                        <hr>
                        <div class="row">
                            <div class="col-sm-3">
                                <p class="mb-0">Adres</p>
                            </div>
                            <div class="col-sm-9">
                                <p class="text-muted mb-0">@Model.Address</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

HR.Presentation/Areas/Personnel/Views/Person/UpdatePerson.cshtml
@using HR.Application.Features.People.ViewModels
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@model PersonDetailVM
@{
    ViewData["Title"] = "Personel Bilgileri Güncelle";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>

    .btn-primary {
        background-color: #5D54A4;
        border-color: mediumpurple;
        color: black;
    }

        .btn-primary:hover {
            background-color: mediumpurple;
            border-color: mediumpurple;
        }

    .btn-outline-primary{
        border-color:mediumpurple;
        color: #5D54A4;
    }
    .btn-outline-primary:hover{
            background-color: #5D54A4;
            border-color: mediumpurple;
            color: black;
    }
</style>

<section>
    <div class="container py-5">
        <div class="row">
            <div class="col-lg-4">
                <div class="card mb-4">
                    <div class="card-body text-center">
                        <img src="~/photos/@Model.Photo" alt="..."
                             class="rounded-circle img-fluid" style="width: 150px;">
                        <h5 class="my-3">@Model.Name @Model.SecondName @Model.Surname @Model.SecondSurname</h5>
                        <p class="text-muted mb-1">@Model.Job.Name</p>
                        <p class="text-muted mb-4">@Model.Department.Name</p>
                        <div class="d-flex justify-content-center mb-2">
                            <a asp-action="UpdatePerson" asp-controller="Person" class="btn btn-primary">Güncelle</a>
                            <a asp-action="Detail" asp-controller="Person" asp-route-id="@Model.Id" class="btn btn-outline-primary ms-1">Detay</a>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-lg-8 grid-margin stretch-card">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title" style="color : #5D54A4;">Kullanıcı Bilgileri Güncelle</h4>
                        <form class="forms-sample" asp-action="UpdatePerson" asp-controller="Person" method="post" enctype="multipart/form-data">
                            <div class="form-group">
                                <label asp-for="PhotoFile" class="control-label">Fotoğraf</label>
                                <input id="fileInput" asp-for="PhotoFile" class="form-control" type="file" onchange="return validateFile();" value="@Model.Photo" />
                                <span asp-validation-for="PhotoFile" class="text-danger"></span>
                            </div>

                            <div class="form-group">
                                <label asp-for="PhoneNumber">Telefon Numarası</label>
                                <input asp-for="PhoneNumber" type="text" class="form-control" placeholder="(___) ___-____" >
                                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
                            </div>

                            <div class="form-group">
                                <label asp-for="Address">Adres</label>
                                <textarea asp-for="Address" class="form-control" id="exampleTextarea1" rows="4"></textarea>
                                <span asp-validation-for="Address" class="text-danger"></span>
                            </div>

                            <div class="form-group" hidden>
                                <label asp-for="Id" class="control-label"></label>
                                <input asp-for="Id" class="form-control" />
                                <span asp-validation-for="Id" class="text-danger"></span>
                            </div>

                            <div class="form-group">
                                <input type="submit" value="Kaydet" class="btn btn-primary me-2" />
                                <a asp-action="Index" class="btn btn-outline-primary">İptal</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
@section Scripts{
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    <script>
        function validateFile() {
            var fileInput = document.getElementById('fileInput'); // İlgili input elementinin id'si
            var fileName = fileInput.value;
            var fileSize = fileInput.files[0].size; // Dosya boyutu bytes cinsinden

            // Dosya türü kontrolü
            var allowedExtensions = /(\.jpg|\.jpeg|\.png)$/i;
            if (!allowedExtensions.test(fileName)) {
                alert('Hata: Sadece JPEG ve PNG dosyaları yükleyebilirsiniz.');
                fileInput.value = '';
                return false;
            }

            // Dosya boyutu kontrolü (25 MB)
            var maxSize = 25 * 1024 * 1024; // 25 MB
            if (fileSize > maxSize) {
                alert('Hata: Dosya boyutu 25 MB\'dan büyük olamaz.');
                fileInput.value = '';
                return false;
            }

            // Bilgi mesajı
            alert('Başarıyla yüklendi: ' + fileName);

            // Geçerli dosya
            return true;
        }
    </script>
}